!PRINT_DATE: Thu 14 Apr 2022 04:26:54 PM KST
MODULE MD_BASIC
IMPLICIT NONE

CONTAINS
  SUBROUTINE f_symmetry(SIGNAL, ROWS, SMTR_SIGNAL) 
  IMPLICIT NONE

    INTEGER :: Z
    INTEGER, INTENT(IN) :: ROWS
    REAL*8, DIMENSION(ROWS), INTENT(IN) :: SIGNAL
    REAL*8, DIMENSION(ROWS) :: SMTR_SIGNAL

    DO Z = 1, ROWS/2
          SMTR_SIGNAL(Z) = SIGNAL(Z+ROWS/2)
    END DO

    DO Z = ROWS/2+1,ROWS
          SMTR_SIGNAL(Z) = SIGNAL(Z-ROWS/2)
    END DO

  END SUBROUTINE 

  SUBROUTINE flip_2d(BSCAN_IMAGE, DIS, ROWS, FLIP_BSCAN) 
  IMPLICIT NONE

    INTEGER :: F
    INTEGER, INTENT(IN) :: DIS,ROWS
    REAL*8, DIMENSION(DIS,ROWS), INTENT(IN) :: BSCAN_IMAGE
    REAL*8, DIMENSION(DIS,ROWS) :: FLIP_BSCAN

    DO F = 1, DIS
          FLIP_BSCAN((DIS-F+1),:) = BSCAN_IMAGE(F,:)
    END DO

  END SUBROUTINE 

  SUBROUTINE flip_1D_INTEGER(SIGNAL, DIS, FLIP_SIGNAL) 
  IMPLICIT NONE

    INTEGER :: F
    INTEGER, INTENT(IN) :: DIS
    INTEGER, DIMENSION(DIS), INTENT(IN) :: SIGNAL
    INTEGER, DIMENSION(DIS) :: FLIP_SIGNAL

    DO F = 1, DIS
          FLIP_SIGNAL(DIS-F+1) = SIGNAL(F)
    END DO

  END SUBROUTINE 

  SUBROUTINE flip_1D_REAL(SIGNAL, DIS, FLIP_SIGNAL) 
  IMPLICIT NONE

    INTEGER :: F
    INTEGER, INTENT(IN) :: DIS
    REAL*8, DIMENSION(DIS), INTENT(IN) :: SIGNAL
    REAL*8, DIMENSION(DIS) :: FLIP_SIGNAL

    DO F = 1, DIS
          FLIP_SIGNAL(DIS-F+1) = SIGNAL(F)
    END DO

  END SUBROUTINE 




END MODULE MD_BASIC
