MODULE MD_INTERPRE
IMPLICIT NONE

CONTAINS
  SUBROUTINE horizon_pick(B_SCAN_IMAGE, DIS, TRA, ROWS, S1, S2, H_1) 
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: DIS
  INTEGER, INTENT(IN) :: TRA
  INTEGER, INTENT(IN) :: ROWS
  INTEGER, INTENT(IN) :: S1
  INTEGER, INTENT(IN) :: S2
 
  REAL*8, DIMENSION(DIS,1,ROWS), INTENT(IN) :: B_SCAN_IMAGE
  
  INTEGER, DIMENSION(DIS) :: H_1
   
  INTEGER :: X, Y

  DO X = 1, DIS
     H_1(X) = S1 + MAXLOC(B_SCAN_IMAGE(X,1,S1:S2),1)
     !PRINT *, MAXLOC(B_SCAN_IMAGE(X,1,S1:S2)), H_1(X)
  END DO 
  
  END SUBROUTINE horizon_pick
END MODULE MD_INTERPRE

