!PRINT_DATE: Thu 14 Apr 2022 04:26:54 PM KST
MODULE MD_MVMEAN
IMPLICIT NONE

CONTAINS

  SUBROUTINE mv_mean(B_SCAN_IMAGE, MV, DIS, ROWS, MV_MEAN_BSCAN) 
  IMPLICIT NONE

  INTEGER :: Z !depth
  INTEGER :: X, XX
  INTEGER :: MV_X

  INTEGER, INTENT(IN) :: DIS
  INTEGER, INTENT(IN) :: ROWS
  INTEGER, INTENT(IN) :: MV !the number of values for moving average
  
  REAL*8, DIMENSION(DIS,1,ROWS), INTENT(IN) :: B_SCAN_IMAGE
  REAL*8, DIMENSION(:,:,:), ALLOCATABLE ::MV_MEAN_BSCAN
  
  REAL*8, DIMENSION(1,1,ROWS) :: TEMP

!    ALLOCATE(MV_MEAN_BSCAN(DIS3,1,ROWS)) 
  
    MV_X = 1

    DO X = 1, DIS, MV   
     
       TEMP(1,1,:) = 0.0
    
    DO Z = 1, ROWS
        TEMP(1,1,Z) = SUM(B_SCAN_IMAGE(X:X+MV-1,1,Z)) / REAL(MV)
    END DO
         MV_MEAN_BSCAN(MV_X,1,:) = TEMP(1,1,:)
         !PRINT *, "MV_X=",MV_X
         MV_X = MV_X + 1
    END DO

! DEALLOCATE(MV_MEAN_BSCAN)
 
  END SUBROUTINE mv_mean

END MODULE MD_MVMEAN



