MODULE MD_MEAN_ASCAN
IMPLICIT NONE

CONTAINS

  SUBROUTINE mean_ascan(B_SCAN_IMAGE, TRA, ROWS, MEAN) 
  IMPLICIT NONE

  INTEGER :: Z !depth

  INTEGER, INTENT(IN) :: TRA
  INTEGER, INTENT(IN) :: ROWS
  REAL*8, DIMENSION(1, TRA,ROWS), INTENT(IN) :: B_SCAN_IMAGE
  
  REAL*8, DIMENSION(ROWS) :: MEAN

   !DO Z = 1, ROWS
   !   PRINT *, Z, B_SCAN_IMAGE(1,1,Z)
   !END DO

   DO Z = 1, ROWS
        MEAN(Z) = SUM(B_SCAN_IMAGE(1,:,Z)) / REAL(SIZE(B_SCAN_IMAGE(1,:,1))) 
   END DO
   
   !DO Z = 1, ROWS
   !   PRINT *, Z,  B_SCAN_IMAGE(1,1,Z), MEAN(Z)  
   !END DO

  END SUBROUTINE mean_ascan

END MODULE MD_MEAN_ASCAN


