MODULE ZERO_PADDING
IMPLICIT NONE


!USE THIS MODULE AFTER CORRECTING ZERO SHIFT
CONTAINS
SUBROUTINE zero_padding(signal,ROWS,signal_ZEROPAD)


INTEGER, INTENT(IN) :: ROWS 
REAL*8, DIMENSION(ROWS), INTENT(IN) :: signal
REAL*8, DIMENSION(ROWS) :: singal_ZEROPAD
REAL*8, DIMENSION(ROWS) :: ZERO_PAD
INTEGER :: Z, T, BAND, k, f_c

!=====ZERO_PADDING=====
!ZERO_PAD = 1.0

!GAUSSIAN 
!BAND = 100
!T = 3
!DO Z = 1, ROWS
!   ZERO_PAD(Z) = EXP(- (((Z-1)-(BAND * T)) / 2.0 * T) **2)
!END DO 


!BUTTERWORTH
f_c = 400
k = 50
DO Z = 1, ROWS
   ZERO_PAD(Z)  = SQRT(1.0/ (1.0 + ( (REAL(Z)/REAL(f_c))**(2.0 * k) ) ) )
END DO 


!ZERO PADDING
DO Z = 1, ROWS

   signal_ZEROPAD(Z) = signal(Z) * ZERO_PAD(Z)

END DO 

END PROGRAM
