PROGRAM ZERO_PADDING

USE MD_BACKGROUND

IMPLICIT NONE


CHARACTER(120) :: INPUT_PATH
CHARACTER(120) :: OUTPUT_PATH
CHARACTER(120) :: OUTPUT_PATH2



INTEGER, PARAMETER :: ROWS = 616
INTEGER, PARAMETER :: ROWS2 = 512

REAL*8, DIMENSION(ROWS) :: ASCAN
REAL*8, DIMENSION(ROWS) :: ASCAN2
REAL*8, DIMENSION(ROWS) :: ASCAN_ZEROPAD

REAL*8, DIMENSION(ROWS) :: ZERO_PAD


INTEGER :: Z, T, BAND, k, f_c 
REAL*8 :: BGR

INPUT_PATH  = "A_SCOPE_GPR.txt"
OUTPUT_PATH = "A_SCOPE_GPR_ZEROPAD.txt"
OUTPUT_PATH2 = "ZEROPAD_FUNCTION.txt"


OPEN(UNIT=10, FILE = INPUT_PATH, FORM="FORMATTED", STATUS="OLD", ACTION="READ")
OPEN(UNIT=20, FILE = OUTPUT_PATH, STATUS='REPLACE', ACTION='WRITE')
OPEN(UNIT=30, FILE = OUTPUT_PATH2, STATUS='REPLACE', ACTION='WRITE')

!READ
READ(10,*) ASCAN


!REMOVE THE BACKGROUND
 CALL background(ASCAN, ROWS, 501,600, BGR)
 ASCAN2 = ASCAN - BGR
 PRINT *, "BACKGROUND=", BGR
   

!=====ZERO_PADDING=====

!ZERO_PAD = 1.0

!GAUSSIAN 
!BAND = 100
!T = 3
!DO Z = 1, ROWS
!   ZERO_PAD(Z) = EXP(- (((Z-1)-(BAND * T)) / 2.0 * T) **2)
!END DO 


!BUTTERWORTH
f_c = 450
k = 50
DO Z = 1, ROWS
   ZERO_PAD(Z)  = SQRT(1.0/ (1.0 + ( (REAL(Z)/REAL(f_c))**(2.0 * k) ) ) )
END DO 


!ZERO PADDING

DO Z = 1, ROWS

   ASCAN_ZEROPAD(Z) = ASCAN2(Z) * ZERO_PAD(Z)

END DO 

!WRITE
DO Z = 2, ROWS2+1   
!THE FIRST DATA FROM AN A-SCOPE OF GPR HAS ZERO VALUE.
!SO THAT I WRITE THE DATA FROM 2 TO REMOVE IT.

   WRITE(20,*) ASCAN_ZEROPAD(Z)
END DO 


DO Z = 1, ROWS
   WRITE(30,*) ZERO_PAD(Z)
END DO 



END PROGRAM
